[package]
name = "rftps"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
libunftp = "0.20.3"
unftp-sbe-fs = "0.2.6"
rand = "0.9.0"
